import assert from 'node:assert/strict';
import {execFile} from 'node:child_process';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {promisify} from 'node:util';
import test from 'node:test';
const execute=promisify(execFile),cli=new URL('../bin/chill-agent.mjs',import.meta.url).pathname;
async function fixture(t){
 const root=await mkdtemp(join(tmpdir(),'chill-goals-'));t.after(()=>rm(root,{recursive:true,force:true}));
 const env={...process.env,CHILL_AGENT_DATA_DIR:root,CHILL_AGENT_CODEX_PATH:'/missing/codex'};
 const invoke=(...args)=>execute(process.execPath,[cli,...args],{env});
 const run=async(...args)=>JSON.parse((await invoke(...args)).stdout);
 let serial=0;
 const update=async(id,patch)=>{const file=join(root,`patch-${serial++}.json`);await writeFile(file,JSON.stringify(patch));return run('update','--id',id,'--input-file',file);};
 const feedback=async(id,input)=>{const file=join(root,`feedback-${serial++}.json`);await writeFile(file,JSON.stringify(input));return (await invoke('feedback','--id',id,'--input-file',file)).stdout.trim().split('\n').map(JSON.parse)[0].feedback;};
 const brief=async(id,body)=>{const {path}=await run('brief','path','--id',id);await writeFile(path,body);return run('brief','update','--id',id);};
 return {root,run,invoke,update,feedback,brief};
}
test('empty Goals accept Conversation; stable Markdown updates only publish changes',async t=>{
 const f=await fixture(t),goal=await f.run('create','--title','Stable Goal');
 assert.equal(await readFile(goal.briefPath,'utf8'),'');
 assert.equal((await f.run('show','--id','1')).brief,null);
 await f.run('comment','--id','1','--text','Before Brief');
 const first=await f.brief('1','# Plan\n\nOriginal'),path=join(f.root,'workspace/goals/1/briefs/v1.json'),bytes=await readFile(path,'utf8');
 assert.equal(first.changed,true);
 const unchanged=await f.run('brief','update','--id','1');assert.equal(unchanged.changed,false);assert.equal(unchanged.version,1);
 await writeFile(goal.briefPath,'# Plan\n\nEdited');
 assert.equal((await f.run('show','--id','1')).brief.body,'# Plan\n\nOriginal','unpublished edits stay local');
 await f.run('brief','update','--id','1');
 await f.run('comment','--id','1','--text','After update');
 const past=await f.run('show','--id','1','--version','1');
 assert.equal(past.goal.title,'Stable Goal');assert.equal(past.brief.body,first.body);
 assert.equal(past.conversation.length,2);assert.equal(past.latestVersion,2);
 assert.equal(await readFile(path,'utf8'),bytes);
});
test('typed Agent posts require a title for Letters and no legacy entrypoints are supported',async t=>{
 const f=await fixture(t);await f.run('create','--title','Root');
 await assert.rejects(f.run('letter','--id','1','--text','A question'),/title.*required/);
 await assert.rejects(f.run('comment','--id','1','--title','title','--text','x'),/Unknown option/);
 for(const command of ['note','reply','reopen'])await assert.rejects(f.run(command,'--id','1'),/Unknown command/);
 await f.run('letter','--id','1','--title','Which way?','--text','Would you prefer A or B?');
 const page=await f.run('show','--id','1');assert.equal(page.letters.length,1);assert.equal(page.brief,null);
 assert.equal(page.conversation[0].type,'letter');assert.equal(page.conversation[0].version,undefined);
});
test('explicit answers close only targeted Letters; unrelated comments and Brief never close them',async t=>{
 const f=await fixture(t);await f.run('create','--title','Root');
 const a=await f.run('letter','--id','1','--title','A','--text','A?'),b=await f.run('letter','--id','1','--title','B','--text','B?');
 await f.feedback('1',{text:'Just a comment'});await f.brief('1','Plan');
 assert.equal((await f.run('show','--id','1')).letters.length,2);
 const answer=await f.feedback('1',{text:'Two answers',annotations:[{kind:'letter',source:{kind:'comment',eventId:a.id},text:'A answer'},{kind:'letter',source:{kind:'comment',eventId:b.id},text:'B answer'}],requestId:'answer-request-01'});
 assert.equal((await f.run('show','--id','1')).letters.length,0);
 assert.equal((await f.feedback('1',{text:'Two answers',annotations:[{kind:'letter',source:{kind:'comment',eventId:a.id},text:'A answer'},{kind:'letter',source:{kind:'comment',eventId:b.id},text:'B answer'}],requestId:'answer-request-01'})).id,answer.id);
 await f.run('comment','--id','1','--text','Thanks');assert.equal((await f.run('tree'))[0].letterCount,0);
 const followup=await f.run('letter','--id','1','--title','One more','--text','Another choice?');
 assert.deepEqual((await f.run('show','--id','1')).letters.map(l=>l.id),[followup.id]);
 const delta=await f.run('show','--id','1','--since',String(answer.id-1));assert.equal(delta.answerTargets.length,2);
 await f.run('create','--title','Other');
 await assert.rejects(f.feedback('2',{annotations:[{kind:'letter',source:{kind:'comment',eventId:a.id},text:'Foreign'}]}),/Letter not found/);
 await assert.rejects(f.feedback('1',{annotations:[{kind:'letter',source:{kind:'comment',eventId:a.id},text:'One'},{kind:'letter',source:{kind:'comment',eventId:a.id},text:'Two'}]}),/once per comment/);
 await assert.rejects(f.feedback('1',{answers:[{letterId:a.id,text:'Old format'}]}),/Unknown Conversation field/);
 await assert.rejects(f.feedback('1',{annotations:[{kind:'letter',source:{kind:'brief',eventId:a.id},text:'Wrong source'}]}),/Agent Letter/);
 const normal=await f.run('comment','--id','1','--text','Ordinary message');
 await assert.rejects(f.feedback('1',{annotations:[{kind:'letter',source:{kind:'comment',eventId:normal.id},text:'Not a Letter'}]}),/Letter not found/);
 await f.feedback('1',{annotations:[{kind:'text',source:{kind:'comment',eventId:followup.id},anchor:{start:0,end:7,quote:'Another'},text:'A note about the wording'}]});
 assert.equal((await f.run('show','--id','1')).letters.length,1,'quoting Letter text is not an answer');
});
test('parent edits reject missing parents and cycles, including simultaneous reparenting',async t=>{
 const f=await fixture(t);await f.run('create','--title','Root');await f.run('create','--title','Child','--parent','1');
 await assert.rejects(f.run('create','--title','Missing','--parent','9'),/Parent Goal not found/);
 await assert.rejects(f.update('1',{parentId:'2'}),/own ancestor/);
 await f.run('create','--title','Other');
 const outcomes=await Promise.allSettled([f.update('1',{parentId:'3'}),f.update('3',{parentId:'1'})]);
 assert.equal(outcomes.filter(o=>o.status==='fulfilled').length,1);
});
test('Letter titles accept exact text annotations with a distinct source field',async t=>{
 const f=await fixture(t);await f.run('create','--title','Root');await f.run('create','--title','Other');
 const letter=await f.run('letter','--id','1','--title','Title question','--text','Message question');
 const note={kind:'text',source:{kind:'comment',eventId:letter.id,field:'title'},anchor:{start:0,end:5,quote:'Title'},text:'About the title'};
 const saved=await f.feedback('1',{annotations:[note]});
 assert.deepEqual(saved.annotations[0].source,note.source);
 assert.equal((await f.run('show','--id','1')).letters.length,1,'a title annotation is not a Letter answer');
 assert.match((await f.invoke('show','--id','1','--format','text')).stdout,/Annotation · Letter title/);
 const ordinary=await f.run('comment','--id','1','--text','Title question');
 for(const source of [{...note.source,eventId:ordinary.id},{...note.source,field:'other'}])
  await assert.rejects(f.feedback('1',{annotations:[{...note,source}]}),/Annotation/);
 await assert.rejects(f.feedback('2',{annotations:[note]}),/Annotation/);
 await assert.rejects(f.feedback('1',{annotations:[{...note,anchor:{start:0,end:7,quote:'Message'}}]}),/Annotation/);
 await assert.rejects(f.feedback('1',{annotations:[{...note,source:{kind:'comment',eventId:letter.id}}]}),/Annotation/);
 await f.run('close-letter','--id','1','--event',String(letter.id));
 await f.feedback('1',{annotations:[note]});
 assert.equal((await f.run('show','--id','1')).letters.length,0);
});
test('Agent receipt preserves the Letter and its annotation targets; counts and cursors update without a user answer',async t=>{
 const f=await fixture(t);await f.run('create','--title','Root');await f.run('create','--title','Child','--parent','1');
 await f.update('2',{state:'waiting',waitReason:'Independent prerequisite'});
 const a=await f.run('letter','--id','1','--title','Choice','--text','Which option?');
 const child=await f.run('letter','--id','2','--title','Child choice','--text','Which child option?');
 const comment=await f.feedback('1',{text:'The choice is settled in this discussion.'});
 assert.equal((await f.run('tree'))[0].letterCount,2);
 for(const id of ['0','1.5','9007199254740992'])await assert.rejects(f.run('close-letter','--id','1','--event',id),/positive integer/);
 await assert.rejects(f.run('close-letter','--id','1','--event',String(child.id)),/Letter not found/);
 await assert.rejects(f.run('close-letter','--id','1','--event',String(comment.id)),/Letter not found/);
 const results=await Promise.all(Array.from({length:4},()=>f.run('close-letter','--id','1','--event',String(a.id),'--reason','No further answer or visibility is needed.')));
 assert.equal(results.filter(r=>r.changed).length,1);assert.ok(results.every(r=>r.status==='received'));
 const received=results[0];assert.equal(received.id,a.id);assert.equal(received.updatedAt,a.updatedAt);assert.equal(received.text,a.text);assert.equal(received.changeId,comment.id+1);
 let page=await f.run('show','--id','1','--since',String(comment.id));
 assert.deepEqual(page.conversation.map(e=>e.id),[a.id]);assert.equal(page.conversationInfo.cursor,received.changeId);
 assert.deepEqual(page.letters.map(l=>l.id),[child.id]);assert.equal(page.conversation[0].receiveReason,'No further answer or visibility is needed.');
 assert.equal((await f.run('tree'))[0].children[0].state,'waiting');
 assert.equal((await f.run('check','--since',String(comment.id))).count,0);
 const next=await f.run('comment','--id','1','--text','Receipt recorded.');assert.equal(next.id,received.changeId+1);
 const annotation={kind:'text',source:{kind:'comment',eventId:a.id},anchor:{start:0,end:5,quote:'Which'},text:'Still the same question'};
 await f.feedback('1',{annotations:[annotation]});
 page=await f.run('show','--id','1');assert.equal(page.conversation.filter(e=>e.id===a.id).length,1);
 assert.equal(page.conversation.filter(e=>e.author==='user').length,2,'receipt does not fabricate an answer');
 assert.equal(page.conversation.find(e=>e.id===a.id).receivedAt,received.receivedAt);
 await f.feedback('2',{annotations:[{kind:'letter',source:{kind:'comment',eventId:child.id},text:'Explicit answer'}]});
 const answered=await f.run('close-letter','--id','2','--event',String(child.id));
 assert.equal(answered.changed,false);assert.equal(answered.status,'answered');assert.equal(answered.receivedAt,undefined);
 assert.equal((await f.run('tree'))[0].letterCount,0);
});
test('concurrent Goal creation and identical Brief updates allocate without duplicates',async t=>{
 const f=await fixture(t);const goals=await Promise.all(Array.from({length:4},()=>f.run('create','--title','Goal')));
 assert.deepEqual(goals.map(g=>g.id).sort(),['1','2','3','4']);
 await writeFile(goals.find(g=>g.id==='1').briefPath,'# Current');
 const saved=await Promise.all(Array.from({length:4},()=>f.run('brief','update','--id','1')));
 assert.equal(saved.filter(s=>s.changed).length,1);assert.ok(saved.every(s=>s.version===1));
 await assert.rejects(f.update('1',{state:'working'}),/Live Working/);
 await assert.rejects(f.update('1',{state:'waiting'}),/Waiting reason/);
});
test('completed leaf count is independent of Brief, comments and Letter answers',async t=>{
 const f=await fixture(t);await f.run('create','--title','Root');
 for(const title of ['Done','Started','Waiting'])await f.run('create','--title',title,'--parent','1');
 await f.update('2',{state:'done'});await f.update('3',{started:true});await f.update('4',{state:'waiting',waitReason:'Input'});
 const letter=await f.run('letter','--id','4','--title','Choice','--text','Which one?');await f.brief('3','Progress');
 assert.equal((await f.run('tree'))[0].progress,33);
 await f.feedback('4',{annotations:[{kind:'letter',source:{kind:'comment',eventId:letter.id},text:'A'}]});
 let tree=(await f.run('tree'))[0];assert.equal(tree.progress,33);assert.equal(tree.children[2].state,'waiting');
 await f.update('3',{state:'done'});assert.equal((await f.run('tree'))[0].progress,67);
 await f.update('4',{state:'done'});tree=(await f.run('tree'))[0];assert.equal(tree.progress,99);assert.equal(tree.state,'idle');
 await f.update('1',{state:'done'});tree=(await f.run('tree'))[0];assert.equal(tree.progress,100);assert.equal(tree.state,'done');
});
test('Done requires all descendants; reopening or adding children reopens only Done ancestors',async t=>{
 const f=await fixture(t);
 await f.run('create','--title','Root','--criteria','Whole outcome');
 await f.run('create','--title','Branch','--parent','1','--criteria','Branch outcome');
 await f.run('create','--title','Leaf','--parent','2');
 await f.run('create','--title','Sibling','--parent','1');
 await assert.rejects(f.update('1',{state:'done'}),/unfinished SubGoals.*#2.*#3.*#4/);
 assert.equal((await f.run('show','--id','1')).goal.state,'idle');
 await f.update('3',{state:'done'});
 let saved=await f.update('2',{state:'done'});
 assert.deepEqual(saved.nextActions.ancestors.map(a=>[a.id,a.criteria,a.state]),[['1','Whole outcome','idle']]);
 await assert.rejects(f.update('1',{state:'done'}),/#4 "Sibling"/);
 await f.update('4',{state:'done'});await f.update('1',{state:'done'});
 await f.update('3',{state:'waiting',waitReason:'Recheck'});
 let tree=(await f.run('tree'))[0];
 assert.equal((await f.run('show','--id','1')).root.state,'waiting');
 for(const id of ['1','2'])assert.equal(JSON.parse(await readFile(join(f.root,`workspace/goals/${id}/goal.json`))).state,'idle');
 assert.equal(tree.children[1].state,'done','unrelated sibling remains complete');
 await f.update('3',{state:'done'});await f.update('2',{state:'done'});await f.update('1',{state:'done'});
 await f.run('create','--title','New leaf','--parent','2');
 for(const id of ['1','2'])assert.equal(JSON.parse(await readFile(join(f.root,`workspace/goals/${id}/goal.json`))).state,'idle');
 assert.equal((await f.run('tree'))[0].children[1].state,'done');
 await f.run('create','--title','Other root');await f.update('6',{state:'done'});
 await f.update('4',{parentId:'6'});
 assert.equal(JSON.parse(await readFile(join(f.root,'workspace/goals/6/goal.json'))).state,'idle','moving even a Done child changes its new parent scope');
});
test('concurrent child creation and parent completion never leave Done over an unfinished child',async t=>{
 const f=await fixture(t);await f.run('create','--title','Root');
 await Promise.allSettled([f.update('1',{state:'done'}),f.run('create','--title','Added concurrently','--parent','1')]);
 const tree=(await f.run('tree'))[0];assert.equal(tree.state,'idle');assert.equal(tree.children.length,1);
 await assert.rejects(f.update('1',{state:'done'}),/unfinished SubGoals/);
});
test('runtime rejects obsolete schemas without modifying data',async t=>{
 const f=await fixture(t);await f.run('create','--title','Current');
 const path=join(f.root,'workspace/schema.json'),old=JSON.stringify({format:'goal-workspace',version:3});await writeFile(path,old);
 await assert.rejects(f.run('tree'),/Unsupported workspace/);assert.equal(await readFile(path,'utf8'),old);
});
